### ISSUE TITLE
Build failed due to invalid dependency checksum

### ISSUE THREAD

**Issue by bvfalcon** [eclipse-sourceediting/sourceediting#2]
Command `mvn clean package` (Maven 3.9.6) gives an error
<summary>SHA-512 hash is not as expected</summary>
<details>
[INFO] Downloading from p2: https://ci.eclipse.org/webtools/job/webtools-servertools_master/lastSuccessfulBuild/artifact/site/target/repository/plugins/org.eclipse.wst.internet.monitor.core_1.1.0.v202304050316.jar
[INFO] Downloaded from p2: https://ci.eclipse.org/webtools/job/webtools-servertools_master/lastSuccessfulBuild/artifact/site/target/repository/plugins/org.eclipse.wst.internet.monitor.core_1.1.0.v202304050316.jar (77 KB at 25 MB/s)
[ERROR] An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.wst.internet.monitor.core,1.1.0.v202304050316 from repository https://ci.eclipse.org/webtools/job/webtools-servertools_master/lastSuccessfulBuild/artifact/site/target/repository:
[ERROR]    Problems downloading artifact: osgi.bundle,org.eclipse.wst.internet.monitor.core,1.1.0.v202304050316.:
[ERROR]       SHA-512 hash is not as expected. Expected: 613c24fd7bb7252614102cd8de2f68ef7c12da954aa9d793efb7800c49f101c5430cd9294b250a1fbd700459d358c2825bbe946b5a7ef6ea573944393176e6d1 and found cf42b1f12f25c73d74b7757576b852bc0a4245cdbc84edde46d5389d2edeeea994cf878e05b88df9a2a81dd7cec0715e28fb86e0e203b5bfff5e0675745a7cce.
</details>

**Comment by nitind** [comment]
I have not been able to reproduce this (although I don't think we use the `package` goal). Are you using a version of Tycho earlier than 4.0.4?

**Comment by bvfalcon** [comment]
No, I don't use Tycho directly, I run `mvn` command from console and Maven uses settings and dependencies (including Tycho) that are defined in its pom.xml-files.
More details: Maven 3.9.6, OpenJDK 17.0.9, linux

**Comment by nitind** [comment]
I was only able to reproduce this with an older version of Tycho than mentioned in CONTRIBUTING.md. Regardless, the default has been bumped to the current release and should no longer have this problem.
